"""initial_schema

Revision ID: 0438258645fa
Revises: 
Create Date: 2026-09-24 11:37:26.993219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0438258645fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Category name — must be unique (e.g., Fiction, Computer Science)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False, comment="Unique permission name, e.g. 'book:create', 'user:suspend'. Format is 'resource:action'."),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_permissions_name')
    )
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Role name — must be unique (e.g., ADMIN, LIBRARIAN, STUDENT, GUEST)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4'),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False, comment='User email — must be unique and is used as login identifier'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Argon2id hash. NEVER store plaintext passwords.'),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', 'PENDING_VERIFICATION', name='account_status_enum', create_constraint=True), server_default='PENDING_VERIFICATION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_account_status', 'users', ['account_status'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Audit event identifier'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Actor — NULL for unauthenticated events'),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_CHANGE', 'ACCOUNT_LOCKED', 'USER_CREATED', 'USER_UPDATED', 'USER_SUSPENDED', 'USER_DEACTIVATED', 'ROLE_ASSIGNED', 'ROLE_REVOKED', 'BOOK_CREATED', 'BOOK_UPDATED', 'BOOK_DELETED', 'COPY_ISSUED', 'COPY_RETURNED', 'FINE_ISSUED', 'FINE_WAIVED', 'PERMISSION_GRANTED', 'PERMISSION_REVOKED', name='audit_action_enum', create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment="Entity type affected, e.g. 'User', 'BookCopy'"),
    sa.Column('resource_id', sa.Text(), nullable=True, comment='String representation of the affected resource PK'),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'PARTIAL', name='audit_status_enum', create_constraint=True), server_default='SUCCESS', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Event timestamp — set once on insert, never updated'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_resource_type_id', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_id_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Full title of the book'),
    sa.Column('author', sa.String(length=500), nullable=False, comment='Primary author(s); multiple authors separated by semicolon'),
    sa.Column('isbn', sa.String(length=20), nullable=True, comment='ISBN-13 (preferred) or ISBN-10. Nullable for books without an ISBN.'),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('publication_year', sa.SmallInteger(), nullable=True, comment='4-digit publication year'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index('ix_books_author', 'books', ['author'], unique=False)
    op.create_index('ix_books_category_id', 'books', ['category_id'], unique=False)
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=False)
    op.create_index('ix_books_publication_year', 'books', ['publication_year'], unique=False)
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the refresh token. Never store the raw token.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='uq_user_sessions_token_hash')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_user_id_is_revoked', 'user_sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_table('book_copies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('copy_identifier', sa.String(length=100), nullable=False, comment='Human-readable barcode/label on the physical copy'),
    sa.Column('status', sa.Enum('AVAILABLE', 'BORROWED', 'MAINTENANCE', 'LOST', name='copy_status_enum', create_constraint=True), server_default='AVAILABLE', nullable=False),
    sa.Column('shelf_location', sa.String(length=100), nullable=True, comment="Physical shelf location, e.g. 'A3-Shelf2'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('copy_identifier'),
    sa.UniqueConstraint('copy_identifier', name='uq_book_copies_copy_identifier')
    )
    op.create_index('ix_book_copies_book_id', 'book_copies', ['book_id'], unique=False)
    op.create_index('ix_book_copies_book_id_status', 'book_copies', ['book_id', 'status'], unique=False)
    op.create_index('ix_book_copies_status', 'book_copies', ['status'], unique=False)
    op.create_table('borrow_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who borrowed the copy'),
    sa.Column('book_copy_id', sa.UUID(), nullable=False, comment='The specific physical copy that was borrowed'),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the copy was issued'),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp by which the copy must be returned'),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the copy was actually returned; NULL if still borrowed'),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', 'LOST', name='borrow_status_enum', create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borrow_records_book_copy_id', 'borrow_records', ['book_copy_id'], unique=False)
    op.create_index('ix_borrow_records_book_copy_id_status', 'borrow_records', ['book_copy_id', 'status'], unique=False)
    op.create_index('ix_borrow_records_due_at', 'borrow_records', ['due_at'], unique=False)
    op.create_index('ix_borrow_records_status', 'borrow_records', ['status'], unique=False)
    op.create_index('ix_borrow_records_user_id', 'borrow_records', ['user_id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('borrow_record_id', sa.UUID(), nullable=False, comment='The borrow transaction that generated this fine'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Fine amount in base currency'),
    sa.Column('reason', sa.Enum('OVERDUE', 'LOST', 'DAMAGED', name='fine_reason_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'WAIVED', name='fine_status_enum', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_fines_amount_non_negative'),
    sa.ForeignKeyConstraint(['borrow_record_id'], ['borrow_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('borrow_record_id')
    )
    op.create_index('ix_fines_borrow_record_id', 'fines', ['borrow_record_id'], unique=False)
    op.create_index('ix_fines_status', 'fines', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fines_status', table_name='fines')
    op.drop_index('ix_fines_borrow_record_id', table_name='fines')
    op.drop_table('fines')
    op.drop_index('ix_borrow_records_user_id', table_name='borrow_records')
    op.drop_index('ix_borrow_records_status', table_name='borrow_records')
    op.drop_index('ix_borrow_records_due_at', table_name='borrow_records')
    op.drop_index('ix_borrow_records_book_copy_id_status', table_name='borrow_records')
    op.drop_index('ix_borrow_records_book_copy_id', table_name='borrow_records')
    op.drop_table('borrow_records')
    op.drop_index('ix_book_copies_status', table_name='book_copies')
    op.drop_index('ix_book_copies_book_id_status', table_name='book_copies')
    op.drop_index('ix_book_copies_book_id', table_name='book_copies')
    op.drop_table('book_copies')
    op.drop_index('ix_user_sessions_user_id_is_revoked', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_books_title', table_name='books')
    op.drop_index('ix_books_publication_year', table_name='books')
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_index('ix_books_category_id', table_name='books')
    op.drop_index('ix_books_author', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_audit_logs_user_id_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_account_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
