"""add_mfa_and_password_reset_support

Revision ID: 3741532892a9
Revises: 0438258645fa
Create Date: 2026-09-24 19:49:23.177182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3741532892a9'
down_revision: Union[str, Sequence[str], None] = '0438258645fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Flag indicating if TOTP MFA is active for this account'))
    op.add_column('users', sa.Column('mfa_secret', sa.Text(), nullable=True, comment='Base32 TOTP secret. Never expose in API responses or audit logs.'))
    op.add_column('users', sa.Column('mfa_recovery_codes', sa.JSON(), nullable=True, comment='List of SHA-256 hashes of one-time recovery codes.'))

    # Add new enum values to audit_action_enum
    audit_actions = [
        'PASSWORD_RESET_REQUESTED',
        'PASSWORD_RESET_COMPLETED',
        'PASSWORD_RESET_FAILED',
        'MFA_ENROLLMENT_STARTED',
        'MFA_ENABLED',
        'MFA_VERIFICATION_FAILED',
        'MFA_RECOVERY_USED',
        'MFA_DISABLED',
    ]
    for action in audit_actions:
        op.execute(sa.text(f"ALTER TYPE audit_action_enum ADD VALUE IF NOT EXISTS '{action}'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'is_mfa_enabled')
    # ### end Alembic commands ###
